### ISSUE TITLE
Alignment

### ISSUE THREAD

**Issue by Aalaizah** [lcb931023/pathfinder_random_character_generator#10]
We should also add in character alignment. Lawful, Neutral, Chaotic paired with Good, Neutral, Evil

**Comment by lcb931023** [comment]
Sure! What's this dependent on?

**Comment by Aalaizah** [comment]
Each race has an alignment that they're more likely to be, but it's normally completely up to the player.

**Comment by lcb931023** [comment]
Neat. We can randomly pick one, but allow user to choose other alignments. The form is completely editable.
