### ISSUE TITLE
Dice text parser

### ISSUE THREAD

**Issue by valeatory** [lcb931023/pathfinder_random_character_generator#6]
In some parts of the json, there are randomizations defined by dice+adds. We need a class/method to parse these in the format of 2d6*2+4, meaning the sum of two random numbers between one and six, then multiplied by two, and added to four.

**Comment by lcb931023** [comment]
/(\d+)d(\d_)\_?(\d+)?+?(\d+)?/

**Comment by lcb931023** [comment]
Parser finished. Are there any occasion where the dice rolling notations will have a negative sign in front of it?
