### ISSUE TITLE
Armor Class(AC)

### ISSUE THREAD

**Issue by Aalaizah** [lcb931023/pathfinder_random_character_generator#9]
10 + armor bonus + shield bonus + Dexterity modifier + other modifiers

I think the only two that we need at the start of the game are Natural Armor and Size Modifier

Other Modifiers: Many other factors modify your AC.
Enhancement Bonuses: Enhancement bonuses apply to your armor to increase the armor bonus it provides.
Deflection Bonus: Magical def lection effects ward off attacks and improve your AC.
Natural Armor: If your race has a tough hide, scales, or thick skin you receive a bonus to your AC.
Dodge Bonuses: Dodge bonuses represent actively avoiding blows. Any situation that denies you your Dexterity bonus also denies you dodge bonuses. (Wearing armor, however, does not limit these bonuses the way it limits a Dexterity bonus to AC.) Unlike most sorts of bonuses, dodge bonuses stack with each other.
Size Modifier: You receive a bonus or penalty to your AC based on your size. See Table 8–1.

Size Size Modifier
Colossal –8, Gargantuan –4, Huge –2, Large –1, Medium +0, Small +1, Tiny +2, Diminutive +4, Fine +8

**Comment by Aalaizah** [comment]
Size seems dependent on race

**Comment by valeatory** [comment]
Closed with 1284c400a2f28de3cb760e3e2c94c5385d55fe13
